
server:
#????
 servlet:
   port: 8080
   context-path: /bootsyh
spring:
#???????
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        encoding: utf-8
        mode: HTML
        cache: false
#?????druid
    datasource:
        name: boot
        url: jdbc:mysql://localhost:3306/hcp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  #????xml???
  mapper-locations: classpath:mapper/*.xml
  #????
  #type-aliases-package: com.cn.ljt.entity
#???
#logging:
 # config: classpath:logback-spring.xml
  #level:
    #dao: debug
    #org:
      #mybatis: debug